// Code generated by 'yaegi extract github.com/gotd/td/telegram/message/markup'. DO NOT EDIT.

package yaegi

import (
	"github.com/gotd/td/telegram/message/markup"
	"reflect"
)

func init() {
	Symbols["github.com/gotd/td/telegram/message/markup/markup"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BuildKeyboard":      reflect.ValueOf(markup.BuildKeyboard),
		"Button":             reflect.ValueOf(markup.Button),
		"Buy":                reflect.ValueOf(markup.Buy),
		"Callback":           reflect.ValueOf(markup.Callback),
		"ForceReply":         reflect.ValueOf(markup.ForceReply),
		"Game":               reflect.ValueOf(markup.Game),
		"Hide":               reflect.ValueOf(markup.Hide),
		"InlineKeyboard":     reflect.ValueOf(markup.InlineKeyboard),
		"InlineRow":          reflect.ValueOf(markup.InlineRow),
		"Keyboard":           reflect.ValueOf(markup.Keyboard),
		"RequestGeoLocation": reflect.ValueOf(markup.RequestGeoLocation),
		"RequestPhone":       reflect.ValueOf(markup.RequestPhone),
		"RequestPoll":        reflect.ValueOf(markup.RequestPoll),
		"Row":                reflect.ValueOf(markup.Row),
		"SelectiveHide":      reflect.ValueOf(markup.SelectiveHide),
		"SingleRow":          reflect.ValueOf(markup.SingleRow),
		"SwitchInline":       reflect.ValueOf(markup.SwitchInline),
		"URL":                reflect.ValueOf(markup.URL),
		"URLAuth":            reflect.ValueOf(markup.URLAuth),

		// type definitions
		"ReplyKeyboardMarkupBuilder": reflect.ValueOf((*markup.ReplyKeyboardMarkupBuilder)(nil)),
	}
}
