// Code generated by 'yaegi extract github.com/gotd/td/telegram/message/entity'. DO NOT EDIT.

package yaegi

import (
	"github.com/gotd/td/telegram/message/entity"
	"reflect"
)

func init() {
	Symbols["github.com/gotd/td/telegram/message/entity"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BankCard":      reflect.ValueOf(entity.BankCard),
		"Blockquote":    reflect.ValueOf(entity.Blockquote),
		"Bold":          reflect.ValueOf(entity.Bold),
		"BotCommand":    reflect.ValueOf(entity.BotCommand),
		"Cashtag":       reflect.ValueOf(entity.Cashtag),
		"Code":          reflect.ValueOf(entity.Code),
		"ComputeLength": reflect.ValueOf(entity.ComputeLength),
		"Email":         reflect.ValueOf(entity.Email),
		"HTML":          reflect.ValueOf(entity.HTML),
		"Hashtag":       reflect.ValueOf(entity.Hashtag),
		"Italic":        reflect.ValueOf(entity.Italic),
		"Mention":       reflect.ValueOf(entity.Mention),
		"MentionName":   reflect.ValueOf(entity.MentionName),
		"Phone":         reflect.ValueOf(entity.Phone),
		"Pre":           reflect.ValueOf(entity.Pre),
		"Strike":        reflect.ValueOf(entity.Strike),
		"TextURL":       reflect.ValueOf(entity.TextURL),
		"URL":           reflect.ValueOf(entity.URL),
		"Underline":     reflect.ValueOf(entity.Underline),

		// type definitions
		"Builder":   reflect.ValueOf((*entity.Builder)(nil)),
		"Formatter": reflect.ValueOf((*entity.Formatter)(nil)),
	}
}
