// Code generated by 'yaegi extract github.com/gotd/td/tg/e2e'. DO NOT EDIT.

package yaegi

import (
	"context"
	"github.com/gotd/td/bin"
	"github.com/gotd/td/tg/e2e"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/gotd/td/tg/e2e"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BoolFalseTypeID":                                reflect.ValueOf(constant.MakeFromLiteral("3162085175", token.INT, 0)),
		"BoolTrueTypeID":                                 reflect.ValueOf(constant.MakeFromLiteral("2574415285", token.INT, 0)),
		"BytesTypeID":                                    reflect.ValueOf(constant.MakeFromLiteral("3912743810", token.INT, 0)),
		"DecodeBool":                                     reflect.ValueOf(e2e.DecodeBool),
		"DecodeDecryptedMessage":                         reflect.ValueOf(e2e.DecodeDecryptedMessage),
		"DecodeDecryptedMessageAction":                   reflect.ValueOf(e2e.DecodeDecryptedMessageAction),
		"DecodeDecryptedMessageMedia":                    reflect.ValueOf(e2e.DecodeDecryptedMessageMedia),
		"DecodeDocumentAttribute":                        reflect.ValueOf(e2e.DecodeDocumentAttribute),
		"DecodeFileLocation":                             reflect.ValueOf(e2e.DecodeFileLocation),
		"DecodeInputStickerSet":                          reflect.ValueOf(e2e.DecodeInputStickerSet),
		"DecodeMessageEntity":                            reflect.ValueOf(e2e.DecodeMessageEntity),
		"DecodePhotoSize":                                reflect.ValueOf(e2e.DecodePhotoSize),
		"DecodeSendMessageAction":                        reflect.ValueOf(e2e.DecodeSendMessageAction),
		"DecryptedMessage23TypeID":                       reflect.ValueOf(constant.MakeFromLiteral("541931640", token.INT, 0)),
		"DecryptedMessage46TypeID":                       reflect.ValueOf(constant.MakeFromLiteral("917541342", token.INT, 0)),
		"DecryptedMessage8TypeID":                        reflect.ValueOf(constant.MakeFromLiteral("528568095", token.INT, 0)),
		"DecryptedMessageActionAbortKeyTypeID":           reflect.ValueOf(constant.MakeFromLiteral("3708152939", token.INT, 0)),
		"DecryptedMessageActionAcceptKeyTypeID":          reflect.ValueOf(constant.MakeFromLiteral("1877046107", token.INT, 0)),
		"DecryptedMessageActionCommitKeyTypeID":          reflect.ValueOf(constant.MakeFromLiteral("3962440603", token.INT, 0)),
		"DecryptedMessageActionDeleteMessagesTypeID":     reflect.ValueOf(constant.MakeFromLiteral("1700872964", token.INT, 0)),
		"DecryptedMessageActionFlushHistoryTypeID":       reflect.ValueOf(constant.MakeFromLiteral("1729750108", token.INT, 0)),
		"DecryptedMessageActionNoopTypeID":               reflect.ValueOf(constant.MakeFromLiteral("2821709155", token.INT, 0)),
		"DecryptedMessageActionNotifyLayerTypeID":        reflect.ValueOf(constant.MakeFromLiteral("4077160579", token.INT, 0)),
		"DecryptedMessageActionReadMessagesTypeID":       reflect.ValueOf(constant.MakeFromLiteral("206520510", token.INT, 0)),
		"DecryptedMessageActionRequestKeyTypeID":         reflect.ValueOf(constant.MakeFromLiteral("4090061083", token.INT, 0)),
		"DecryptedMessageActionResendTypeID":             reflect.ValueOf(constant.MakeFromLiteral("1360072880", token.INT, 0)),
		"DecryptedMessageActionScreenshotMessagesTypeID": reflect.ValueOf(constant.MakeFromLiteral("2327966837", token.INT, 0)),
		"DecryptedMessageActionSetMessageTTLTypeID":      reflect.ValueOf(constant.MakeFromLiteral("2708683500", token.INT, 0)),
		"DecryptedMessageActionTypingTypeID":             reflect.ValueOf(constant.MakeFromLiteral("3434247745", token.INT, 0)),
		"DecryptedMessageLayerTypeID":                    reflect.ValueOf(constant.MakeFromLiteral("467867529", token.INT, 0)),
		"DecryptedMessageMediaAudio8TypeID":              reflect.ValueOf(constant.MakeFromLiteral("1619031439", token.INT, 0)),
		"DecryptedMessageMediaAudioTypeID":               reflect.ValueOf(constant.MakeFromLiteral("1474341323", token.INT, 0)),
		"DecryptedMessageMediaContactTypeID":             reflect.ValueOf(constant.MakeFromLiteral("1485441687", token.INT, 0)),
		"DecryptedMessageMediaDocument23TypeID":          reflect.ValueOf(constant.MakeFromLiteral("2962572107", token.INT, 0)),
		"DecryptedMessageMediaDocumentTypeID":            reflect.ValueOf(constant.MakeFromLiteral("2063502050", token.INT, 0)),
		"DecryptedMessageMediaEmptyTypeID":               reflect.ValueOf(constant.MakeFromLiteral("144661578", token.INT, 0)),
		"DecryptedMessageMediaExternalDocumentTypeID":    reflect.ValueOf(constant.MakeFromLiteral("4204114141", token.INT, 0)),
		"DecryptedMessageMediaGeoPointTypeID":            reflect.ValueOf(constant.MakeFromLiteral("893913689", token.INT, 0)),
		"DecryptedMessageMediaPhoto23TypeID":             reflect.ValueOf(constant.MakeFromLiteral("846826124", token.INT, 0)),
		"DecryptedMessageMediaPhotoTypeID":               reflect.ValueOf(constant.MakeFromLiteral("4059729272", token.INT, 0)),
		"DecryptedMessageMediaVenueTypeID":               reflect.ValueOf(constant.MakeFromLiteral("2316170607", token.INT, 0)),
		"DecryptedMessageMediaVideo23TypeID":             reflect.ValueOf(constant.MakeFromLiteral("1380598109", token.INT, 0)),
		"DecryptedMessageMediaVideo8TypeID":              reflect.ValueOf(constant.MakeFromLiteral("1290694387", token.INT, 0)),
		"DecryptedMessageMediaVideoTypeID":               reflect.ValueOf(constant.MakeFromLiteral("2534181902", token.INT, 0)),
		"DecryptedMessageMediaWebPageTypeID":             reflect.ValueOf(constant.MakeFromLiteral("3842314712", token.INT, 0)),
		"DecryptedMessageService8TypeID":                 reflect.ValueOf(constant.MakeFromLiteral("2856858237", token.INT, 0)),
		"DecryptedMessageServiceTypeID":                  reflect.ValueOf(constant.MakeFromLiteral("1930838368", token.INT, 0)),
		"DecryptedMessageTypeID":                         reflect.ValueOf(constant.MakeFromLiteral("2446083700", token.INT, 0)),
		"DocumentAttributeAnimatedTypeID":                reflect.ValueOf(constant.MakeFromLiteral("297109817", token.INT, 0)),
		"DocumentAttributeAudio23TypeID":                 reflect.ValueOf(constant.MakeFromLiteral("85215461", token.INT, 0)),
		"DocumentAttributeAudio45TypeID":                 reflect.ValueOf(constant.MakeFromLiteral("3738310880", token.INT, 0)),
		"DocumentAttributeAudioTypeID":                   reflect.ValueOf(constant.MakeFromLiteral("2555574726", token.INT, 0)),
		"DocumentAttributeFilenameTypeID":                reflect.ValueOf(constant.MakeFromLiteral("358154344", token.INT, 0)),
		"DocumentAttributeImageSizeTypeID":               reflect.ValueOf(constant.MakeFromLiteral("1815593308", token.INT, 0)),
		"DocumentAttributeSticker23TypeID":               reflect.ValueOf(constant.MakeFromLiteral("4211758887", token.INT, 0)),
		"DocumentAttributeStickerTypeID":                 reflect.ValueOf(constant.MakeFromLiteral("978674434", token.INT, 0)),
		"DocumentAttributeVideo66TypeID":                 reflect.ValueOf(constant.MakeFromLiteral("250621158", token.INT, 0)),
		"DocumentAttributeVideoTypeID":                   reflect.ValueOf(constant.MakeFromLiteral("1494273227", token.INT, 0)),
		"DoubleTypeID":                                   reflect.ValueOf(constant.MakeFromLiteral("571523412", token.INT, 0)),
		"FileLocationTypeID":                             reflect.ValueOf(constant.MakeFromLiteral("1406570614", token.INT, 0)),
		"FileLocationUnavailableTypeID":                  reflect.ValueOf(constant.MakeFromLiteral("2086234950", token.INT, 0)),
		"InputStickerSetEmptyTypeID":                     reflect.ValueOf(constant.MakeFromLiteral("4290128789", token.INT, 0)),
		"InputStickerSetShortNameTypeID":                 reflect.ValueOf(constant.MakeFromLiteral("2250033312", token.INT, 0)),
		"IntTypeID":                                      reflect.ValueOf(constant.MakeFromLiteral("2823855066", token.INT, 0)),
		"LongTypeID":                                     reflect.ValueOf(constant.MakeFromLiteral("570911930", token.INT, 0)),
		"MessageEntityBankCardTypeID":                    reflect.ValueOf(constant.MakeFromLiteral("1981704948", token.INT, 0)),
		"MessageEntityBlockquoteTypeID":                  reflect.ValueOf(constant.MakeFromLiteral("34469328", token.INT, 0)),
		"MessageEntityBoldTypeID":                        reflect.ValueOf(constant.MakeFromLiteral("3177253833", token.INT, 0)),
		"MessageEntityBotCommandTypeID":                  reflect.ValueOf(constant.MakeFromLiteral("1827637959", token.INT, 0)),
		"MessageEntityCashtagTypeID":                     reflect.ValueOf(constant.MakeFromLiteral("1280209983", token.INT, 0)),
		"MessageEntityCodeTypeID":                        reflect.ValueOf(constant.MakeFromLiteral("681706865", token.INT, 0)),
		"MessageEntityEmailTypeID":                       reflect.ValueOf(constant.MakeFromLiteral("1692693954", token.INT, 0)),
		"MessageEntityHashtagTypeID":                     reflect.ValueOf(constant.MakeFromLiteral("1868782349", token.INT, 0)),
		"MessageEntityItalicTypeID":                      reflect.ValueOf(constant.MakeFromLiteral("2188348256", token.INT, 0)),
		"MessageEntityMentionNameTypeID":                 reflect.ValueOf(constant.MakeFromLiteral("892193368", token.INT, 0)),
		"MessageEntityMentionTypeID":                     reflect.ValueOf(constant.MakeFromLiteral("4194588573", token.INT, 0)),
		"MessageEntityPhoneTypeID":                       reflect.ValueOf(constant.MakeFromLiteral("2607407947", token.INT, 0)),
		"MessageEntityPreTypeID":                         reflect.ValueOf(constant.MakeFromLiteral("1938967520", token.INT, 0)),
		"MessageEntityStrikeTypeID":                      reflect.ValueOf(constant.MakeFromLiteral("3204879316", token.INT, 0)),
		"MessageEntityTextUrlTypeID":                     reflect.ValueOf(constant.MakeFromLiteral("1990644519", token.INT, 0)),
		"MessageEntityUnderlineTypeID":                   reflect.ValueOf(constant.MakeFromLiteral("2622389899", token.INT, 0)),
		"MessageEntityUnknownTypeID":                     reflect.ValueOf(constant.MakeFromLiteral("3146955413", token.INT, 0)),
		"MessageEntityUrlTypeID":                         reflect.ValueOf(constant.MakeFromLiteral("1859134776", token.INT, 0)),
		"NewClient":                                      reflect.ValueOf(e2e.NewClient),
		"PhotoCachedSizeTypeID":                          reflect.ValueOf(constant.MakeFromLiteral("3920049402", token.INT, 0)),
		"PhotoSizeEmptyTypeID":                           reflect.ValueOf(constant.MakeFromLiteral("236446268", token.INT, 0)),
		"PhotoSizeTypeID":                                reflect.ValueOf(constant.MakeFromLiteral("2009052699", token.INT, 0)),
		"SendMessageCancelActionTypeID":                  reflect.ValueOf(constant.MakeFromLiteral("4250847477", token.INT, 0)),
		"SendMessageChooseContactActionTypeID":           reflect.ValueOf(constant.MakeFromLiteral("1653390447", token.INT, 0)),
		"SendMessageGeoLocationActionTypeID":             reflect.ValueOf(constant.MakeFromLiteral("393186209", token.INT, 0)),
		"SendMessageRecordAudioActionTypeID":             reflect.ValueOf(constant.MakeFromLiteral("3576656887", token.INT, 0)),
		"SendMessageRecordRoundActionTypeID":             reflect.ValueOf(constant.MakeFromLiteral("2297593788", token.INT, 0)),
		"SendMessageRecordVideoActionTypeID":             reflect.ValueOf(constant.MakeFromLiteral("2710034031", token.INT, 0)),
		"SendMessageTypingActionTypeID":                  reflect.ValueOf(constant.MakeFromLiteral("381645902", token.INT, 0)),
		"SendMessageUploadAudioActionTypeID":             reflect.ValueOf(constant.MakeFromLiteral("3870067311", token.INT, 0)),
		"SendMessageUploadDocumentActionTypeID":          reflect.ValueOf(constant.MakeFromLiteral("2410604942", token.INT, 0)),
		"SendMessageUploadPhotoActionTypeID":             reflect.ValueOf(constant.MakeFromLiteral("2567584794", token.INT, 0)),
		"SendMessageUploadRoundActionTypeID":             reflect.ValueOf(constant.MakeFromLiteral("3144779300", token.INT, 0)),
		"SendMessageUploadVideoActionTypeID":             reflect.ValueOf(constant.MakeFromLiteral("2449747959", token.INT, 0)),
		"StringTypeID":                                   reflect.ValueOf(constant.MakeFromLiteral("3039325732", token.INT, 0)),
		"TestDummyFunctionRequestTypeID":                 reflect.ValueOf(constant.MakeFromLiteral("3358947081", token.INT, 0)),
		"TrueTypeID":                                     reflect.ValueOf(constant.MakeFromLiteral("1072550713", token.INT, 0)),
		"TypesConstructorMap":                            reflect.ValueOf(e2e.TypesConstructorMap),
		"TypesMap":                                       reflect.ValueOf(e2e.TypesMap),

		// type definitions
		"BoolBox":                                  reflect.ValueOf((*e2e.BoolBox)(nil)),
		"BoolClass":                                reflect.ValueOf((*e2e.BoolClass)(nil)),
		"BoolFalse":                                reflect.ValueOf((*e2e.BoolFalse)(nil)),
		"BoolTrue":                                 reflect.ValueOf((*e2e.BoolTrue)(nil)),
		"Bytes":                                    reflect.ValueOf((*e2e.Bytes)(nil)),
		"Client":                                   reflect.ValueOf((*e2e.Client)(nil)),
		"DecryptedMessage":                         reflect.ValueOf((*e2e.DecryptedMessage)(nil)),
		"DecryptedMessage23":                       reflect.ValueOf((*e2e.DecryptedMessage23)(nil)),
		"DecryptedMessage46":                       reflect.ValueOf((*e2e.DecryptedMessage46)(nil)),
		"DecryptedMessage8":                        reflect.ValueOf((*e2e.DecryptedMessage8)(nil)),
		"DecryptedMessageActionAbortKey":           reflect.ValueOf((*e2e.DecryptedMessageActionAbortKey)(nil)),
		"DecryptedMessageActionAcceptKey":          reflect.ValueOf((*e2e.DecryptedMessageActionAcceptKey)(nil)),
		"DecryptedMessageActionBox":                reflect.ValueOf((*e2e.DecryptedMessageActionBox)(nil)),
		"DecryptedMessageActionClass":              reflect.ValueOf((*e2e.DecryptedMessageActionClass)(nil)),
		"DecryptedMessageActionCommitKey":          reflect.ValueOf((*e2e.DecryptedMessageActionCommitKey)(nil)),
		"DecryptedMessageActionDeleteMessages":     reflect.ValueOf((*e2e.DecryptedMessageActionDeleteMessages)(nil)),
		"DecryptedMessageActionFlushHistory":       reflect.ValueOf((*e2e.DecryptedMessageActionFlushHistory)(nil)),
		"DecryptedMessageActionNoop":               reflect.ValueOf((*e2e.DecryptedMessageActionNoop)(nil)),
		"DecryptedMessageActionNotifyLayer":        reflect.ValueOf((*e2e.DecryptedMessageActionNotifyLayer)(nil)),
		"DecryptedMessageActionReadMessages":       reflect.ValueOf((*e2e.DecryptedMessageActionReadMessages)(nil)),
		"DecryptedMessageActionRequestKey":         reflect.ValueOf((*e2e.DecryptedMessageActionRequestKey)(nil)),
		"DecryptedMessageActionResend":             reflect.ValueOf((*e2e.DecryptedMessageActionResend)(nil)),
		"DecryptedMessageActionScreenshotMessages": reflect.ValueOf((*e2e.DecryptedMessageActionScreenshotMessages)(nil)),
		"DecryptedMessageActionSetMessageTTL":      reflect.ValueOf((*e2e.DecryptedMessageActionSetMessageTTL)(nil)),
		"DecryptedMessageActionTyping":             reflect.ValueOf((*e2e.DecryptedMessageActionTyping)(nil)),
		"DecryptedMessageBox":                      reflect.ValueOf((*e2e.DecryptedMessageBox)(nil)),
		"DecryptedMessageClass":                    reflect.ValueOf((*e2e.DecryptedMessageClass)(nil)),
		"DecryptedMessageLayer":                    reflect.ValueOf((*e2e.DecryptedMessageLayer)(nil)),
		"DecryptedMessageMediaAudio":               reflect.ValueOf((*e2e.DecryptedMessageMediaAudio)(nil)),
		"DecryptedMessageMediaAudio8":              reflect.ValueOf((*e2e.DecryptedMessageMediaAudio8)(nil)),
		"DecryptedMessageMediaBox":                 reflect.ValueOf((*e2e.DecryptedMessageMediaBox)(nil)),
		"DecryptedMessageMediaClass":               reflect.ValueOf((*e2e.DecryptedMessageMediaClass)(nil)),
		"DecryptedMessageMediaContact":             reflect.ValueOf((*e2e.DecryptedMessageMediaContact)(nil)),
		"DecryptedMessageMediaDocument":            reflect.ValueOf((*e2e.DecryptedMessageMediaDocument)(nil)),
		"DecryptedMessageMediaDocument23":          reflect.ValueOf((*e2e.DecryptedMessageMediaDocument23)(nil)),
		"DecryptedMessageMediaEmpty":               reflect.ValueOf((*e2e.DecryptedMessageMediaEmpty)(nil)),
		"DecryptedMessageMediaExternalDocument":    reflect.ValueOf((*e2e.DecryptedMessageMediaExternalDocument)(nil)),
		"DecryptedMessageMediaGeoPoint":            reflect.ValueOf((*e2e.DecryptedMessageMediaGeoPoint)(nil)),
		"DecryptedMessageMediaPhoto":               reflect.ValueOf((*e2e.DecryptedMessageMediaPhoto)(nil)),
		"DecryptedMessageMediaPhoto23":             reflect.ValueOf((*e2e.DecryptedMessageMediaPhoto23)(nil)),
		"DecryptedMessageMediaVenue":               reflect.ValueOf((*e2e.DecryptedMessageMediaVenue)(nil)),
		"DecryptedMessageMediaVideo":               reflect.ValueOf((*e2e.DecryptedMessageMediaVideo)(nil)),
		"DecryptedMessageMediaVideo23":             reflect.ValueOf((*e2e.DecryptedMessageMediaVideo23)(nil)),
		"DecryptedMessageMediaVideo8":              reflect.ValueOf((*e2e.DecryptedMessageMediaVideo8)(nil)),
		"DecryptedMessageMediaWebPage":             reflect.ValueOf((*e2e.DecryptedMessageMediaWebPage)(nil)),
		"DecryptedMessageService":                  reflect.ValueOf((*e2e.DecryptedMessageService)(nil)),
		"DecryptedMessageService8":                 reflect.ValueOf((*e2e.DecryptedMessageService8)(nil)),
		"DocumentAttributeAnimated":                reflect.ValueOf((*e2e.DocumentAttributeAnimated)(nil)),
		"DocumentAttributeAudio":                   reflect.ValueOf((*e2e.DocumentAttributeAudio)(nil)),
		"DocumentAttributeAudio23":                 reflect.ValueOf((*e2e.DocumentAttributeAudio23)(nil)),
		"DocumentAttributeAudio45":                 reflect.ValueOf((*e2e.DocumentAttributeAudio45)(nil)),
		"DocumentAttributeBox":                     reflect.ValueOf((*e2e.DocumentAttributeBox)(nil)),
		"DocumentAttributeClass":                   reflect.ValueOf((*e2e.DocumentAttributeClass)(nil)),
		"DocumentAttributeFilename":                reflect.ValueOf((*e2e.DocumentAttributeFilename)(nil)),
		"DocumentAttributeImageSize":               reflect.ValueOf((*e2e.DocumentAttributeImageSize)(nil)),
		"DocumentAttributeSticker":                 reflect.ValueOf((*e2e.DocumentAttributeSticker)(nil)),
		"DocumentAttributeSticker23":               reflect.ValueOf((*e2e.DocumentAttributeSticker23)(nil)),
		"DocumentAttributeVideo":                   reflect.ValueOf((*e2e.DocumentAttributeVideo)(nil)),
		"DocumentAttributeVideo66":                 reflect.ValueOf((*e2e.DocumentAttributeVideo66)(nil)),
		"Double":                                   reflect.ValueOf((*e2e.Double)(nil)),
		"FileLocation":                             reflect.ValueOf((*e2e.FileLocation)(nil)),
		"FileLocationBox":                          reflect.ValueOf((*e2e.FileLocationBox)(nil)),
		"FileLocationClass":                        reflect.ValueOf((*e2e.FileLocationClass)(nil)),
		"FileLocationUnavailable":                  reflect.ValueOf((*e2e.FileLocationUnavailable)(nil)),
		"InputStickerSetBox":                       reflect.ValueOf((*e2e.InputStickerSetBox)(nil)),
		"InputStickerSetClass":                     reflect.ValueOf((*e2e.InputStickerSetClass)(nil)),
		"InputStickerSetEmpty":                     reflect.ValueOf((*e2e.InputStickerSetEmpty)(nil)),
		"InputStickerSetShortName":                 reflect.ValueOf((*e2e.InputStickerSetShortName)(nil)),
		"Int":                                      reflect.ValueOf((*e2e.Int)(nil)),
		"Invoker":                                  reflect.ValueOf((*e2e.Invoker)(nil)),
		"Long":                                     reflect.ValueOf((*e2e.Long)(nil)),
		"MessageEntityBankCard":                    reflect.ValueOf((*e2e.MessageEntityBankCard)(nil)),
		"MessageEntityBlockquote":                  reflect.ValueOf((*e2e.MessageEntityBlockquote)(nil)),
		"MessageEntityBold":                        reflect.ValueOf((*e2e.MessageEntityBold)(nil)),
		"MessageEntityBotCommand":                  reflect.ValueOf((*e2e.MessageEntityBotCommand)(nil)),
		"MessageEntityBox":                         reflect.ValueOf((*e2e.MessageEntityBox)(nil)),
		"MessageEntityCashtag":                     reflect.ValueOf((*e2e.MessageEntityCashtag)(nil)),
		"MessageEntityClass":                       reflect.ValueOf((*e2e.MessageEntityClass)(nil)),
		"MessageEntityCode":                        reflect.ValueOf((*e2e.MessageEntityCode)(nil)),
		"MessageEntityEmail":                       reflect.ValueOf((*e2e.MessageEntityEmail)(nil)),
		"MessageEntityHashtag":                     reflect.ValueOf((*e2e.MessageEntityHashtag)(nil)),
		"MessageEntityItalic":                      reflect.ValueOf((*e2e.MessageEntityItalic)(nil)),
		"MessageEntityMention":                     reflect.ValueOf((*e2e.MessageEntityMention)(nil)),
		"MessageEntityMentionName":                 reflect.ValueOf((*e2e.MessageEntityMentionName)(nil)),
		"MessageEntityPhone":                       reflect.ValueOf((*e2e.MessageEntityPhone)(nil)),
		"MessageEntityPre":                         reflect.ValueOf((*e2e.MessageEntityPre)(nil)),
		"MessageEntityStrike":                      reflect.ValueOf((*e2e.MessageEntityStrike)(nil)),
		"MessageEntityTextUrl":                     reflect.ValueOf((*e2e.MessageEntityTextUrl)(nil)),
		"MessageEntityUnderline":                   reflect.ValueOf((*e2e.MessageEntityUnderline)(nil)),
		"MessageEntityUnknown":                     reflect.ValueOf((*e2e.MessageEntityUnknown)(nil)),
		"MessageEntityUrl":                         reflect.ValueOf((*e2e.MessageEntityUrl)(nil)),
		"PhotoCachedSize":                          reflect.ValueOf((*e2e.PhotoCachedSize)(nil)),
		"PhotoSize":                                reflect.ValueOf((*e2e.PhotoSize)(nil)),
		"PhotoSizeBox":                             reflect.ValueOf((*e2e.PhotoSizeBox)(nil)),
		"PhotoSizeClass":                           reflect.ValueOf((*e2e.PhotoSizeClass)(nil)),
		"PhotoSizeEmpty":                           reflect.ValueOf((*e2e.PhotoSizeEmpty)(nil)),
		"SendMessageActionBox":                     reflect.ValueOf((*e2e.SendMessageActionBox)(nil)),
		"SendMessageActionClass":                   reflect.ValueOf((*e2e.SendMessageActionClass)(nil)),
		"SendMessageCancelAction":                  reflect.ValueOf((*e2e.SendMessageCancelAction)(nil)),
		"SendMessageChooseContactAction":           reflect.ValueOf((*e2e.SendMessageChooseContactAction)(nil)),
		"SendMessageGeoLocationAction":             reflect.ValueOf((*e2e.SendMessageGeoLocationAction)(nil)),
		"SendMessageRecordAudioAction":             reflect.ValueOf((*e2e.SendMessageRecordAudioAction)(nil)),
		"SendMessageRecordRoundAction":             reflect.ValueOf((*e2e.SendMessageRecordRoundAction)(nil)),
		"SendMessageRecordVideoAction":             reflect.ValueOf((*e2e.SendMessageRecordVideoAction)(nil)),
		"SendMessageTypingAction":                  reflect.ValueOf((*e2e.SendMessageTypingAction)(nil)),
		"SendMessageUploadAudioAction":             reflect.ValueOf((*e2e.SendMessageUploadAudioAction)(nil)),
		"SendMessageUploadDocumentAction":          reflect.ValueOf((*e2e.SendMessageUploadDocumentAction)(nil)),
		"SendMessageUploadPhotoAction":             reflect.ValueOf((*e2e.SendMessageUploadPhotoAction)(nil)),
		"SendMessageUploadRoundAction":             reflect.ValueOf((*e2e.SendMessageUploadRoundAction)(nil)),
		"SendMessageUploadVideoAction":             reflect.ValueOf((*e2e.SendMessageUploadVideoAction)(nil)),
		"String":                                   reflect.ValueOf((*e2e.String)(nil)),
		"TestDummyFunctionRequest":                 reflect.ValueOf((*e2e.TestDummyFunctionRequest)(nil)),
		"True":                                     reflect.ValueOf((*e2e.True)(nil)),

		// interface wrapper definitions
		"_BoolClass":                   reflect.ValueOf((*_github_com_gotd_td_tg_e2e_BoolClass)(nil)),
		"_DecryptedMessageActionClass": reflect.ValueOf((*_github_com_gotd_td_tg_e2e_DecryptedMessageActionClass)(nil)),
		"_DecryptedMessageClass":       reflect.ValueOf((*_github_com_gotd_td_tg_e2e_DecryptedMessageClass)(nil)),
		"_DecryptedMessageMediaClass":  reflect.ValueOf((*_github_com_gotd_td_tg_e2e_DecryptedMessageMediaClass)(nil)),
		"_DocumentAttributeClass":      reflect.ValueOf((*_github_com_gotd_td_tg_e2e_DocumentAttributeClass)(nil)),
		"_FileLocationClass":           reflect.ValueOf((*_github_com_gotd_td_tg_e2e_FileLocationClass)(nil)),
		"_InputStickerSetClass":        reflect.ValueOf((*_github_com_gotd_td_tg_e2e_InputStickerSetClass)(nil)),
		"_Invoker":                     reflect.ValueOf((*_github_com_gotd_td_tg_e2e_Invoker)(nil)),
		"_MessageEntityClass":          reflect.ValueOf((*_github_com_gotd_td_tg_e2e_MessageEntityClass)(nil)),
		"_PhotoSizeClass":              reflect.ValueOf((*_github_com_gotd_td_tg_e2e_PhotoSizeClass)(nil)),
		"_SendMessageActionClass":      reflect.ValueOf((*_github_com_gotd_td_tg_e2e_SendMessageActionClass)(nil)),
	}
}

// _github_com_gotd_td_tg_e2e_BoolClass is an interface wrapper for BoolClass type
type _github_com_gotd_td_tg_e2e_BoolClass struct {
	WDecode func(b *bin.Buffer) error
	WEncode func(b *bin.Buffer) error
	WString func() string
	WTypeID func() uint32
	WZero   func() bool
}

func (W _github_com_gotd_td_tg_e2e_BoolClass) Decode(b *bin.Buffer) error { return W.WDecode(b) }
func (W _github_com_gotd_td_tg_e2e_BoolClass) Encode(b *bin.Buffer) error { return W.WEncode(b) }
func (W _github_com_gotd_td_tg_e2e_BoolClass) String() string             { return W.WString() }
func (W _github_com_gotd_td_tg_e2e_BoolClass) TypeID() uint32             { return W.WTypeID() }
func (W _github_com_gotd_td_tg_e2e_BoolClass) Zero() bool                 { return W.WZero() }

// _github_com_gotd_td_tg_e2e_DecryptedMessageActionClass is an interface wrapper for DecryptedMessageActionClass type
type _github_com_gotd_td_tg_e2e_DecryptedMessageActionClass struct {
	WDecode func(b *bin.Buffer) error
	WEncode func(b *bin.Buffer) error
	WString func() string
	WTypeID func() uint32
	WZero   func() bool
}

func (W _github_com_gotd_td_tg_e2e_DecryptedMessageActionClass) Decode(b *bin.Buffer) error {
	return W.WDecode(b)
}
func (W _github_com_gotd_td_tg_e2e_DecryptedMessageActionClass) Encode(b *bin.Buffer) error {
	return W.WEncode(b)
}
func (W _github_com_gotd_td_tg_e2e_DecryptedMessageActionClass) String() string { return W.WString() }
func (W _github_com_gotd_td_tg_e2e_DecryptedMessageActionClass) TypeID() uint32 { return W.WTypeID() }
func (W _github_com_gotd_td_tg_e2e_DecryptedMessageActionClass) Zero() bool     { return W.WZero() }

// _github_com_gotd_td_tg_e2e_DecryptedMessageClass is an interface wrapper for DecryptedMessageClass type
type _github_com_gotd_td_tg_e2e_DecryptedMessageClass struct {
	WDecode      func(b *bin.Buffer) error
	WEncode      func(b *bin.Buffer) error
	WGetRandomID func() (value int64)
	WString      func() string
	WTypeID      func() uint32
	WZero        func() bool
}

func (W _github_com_gotd_td_tg_e2e_DecryptedMessageClass) Decode(b *bin.Buffer) error {
	return W.WDecode(b)
}
func (W _github_com_gotd_td_tg_e2e_DecryptedMessageClass) Encode(b *bin.Buffer) error {
	return W.WEncode(b)
}
func (W _github_com_gotd_td_tg_e2e_DecryptedMessageClass) GetRandomID() (value int64) {
	return W.WGetRandomID()
}
func (W _github_com_gotd_td_tg_e2e_DecryptedMessageClass) String() string { return W.WString() }
func (W _github_com_gotd_td_tg_e2e_DecryptedMessageClass) TypeID() uint32 { return W.WTypeID() }
func (W _github_com_gotd_td_tg_e2e_DecryptedMessageClass) Zero() bool     { return W.WZero() }

// _github_com_gotd_td_tg_e2e_DecryptedMessageMediaClass is an interface wrapper for DecryptedMessageMediaClass type
type _github_com_gotd_td_tg_e2e_DecryptedMessageMediaClass struct {
	WDecode func(b *bin.Buffer) error
	WEncode func(b *bin.Buffer) error
	WString func() string
	WTypeID func() uint32
	WZero   func() bool
}

func (W _github_com_gotd_td_tg_e2e_DecryptedMessageMediaClass) Decode(b *bin.Buffer) error {
	return W.WDecode(b)
}
func (W _github_com_gotd_td_tg_e2e_DecryptedMessageMediaClass) Encode(b *bin.Buffer) error {
	return W.WEncode(b)
}
func (W _github_com_gotd_td_tg_e2e_DecryptedMessageMediaClass) String() string { return W.WString() }
func (W _github_com_gotd_td_tg_e2e_DecryptedMessageMediaClass) TypeID() uint32 { return W.WTypeID() }
func (W _github_com_gotd_td_tg_e2e_DecryptedMessageMediaClass) Zero() bool     { return W.WZero() }

// _github_com_gotd_td_tg_e2e_DocumentAttributeClass is an interface wrapper for DocumentAttributeClass type
type _github_com_gotd_td_tg_e2e_DocumentAttributeClass struct {
	WDecode func(b *bin.Buffer) error
	WEncode func(b *bin.Buffer) error
	WString func() string
	WTypeID func() uint32
	WZero   func() bool
}

func (W _github_com_gotd_td_tg_e2e_DocumentAttributeClass) Decode(b *bin.Buffer) error {
	return W.WDecode(b)
}
func (W _github_com_gotd_td_tg_e2e_DocumentAttributeClass) Encode(b *bin.Buffer) error {
	return W.WEncode(b)
}
func (W _github_com_gotd_td_tg_e2e_DocumentAttributeClass) String() string { return W.WString() }
func (W _github_com_gotd_td_tg_e2e_DocumentAttributeClass) TypeID() uint32 { return W.WTypeID() }
func (W _github_com_gotd_td_tg_e2e_DocumentAttributeClass) Zero() bool     { return W.WZero() }

// _github_com_gotd_td_tg_e2e_FileLocationClass is an interface wrapper for FileLocationClass type
type _github_com_gotd_td_tg_e2e_FileLocationClass struct {
	WDecode      func(b *bin.Buffer) error
	WEncode      func(b *bin.Buffer) error
	WGetLocalID  func() (value int)
	WGetSecret   func() (value int64)
	WGetVolumeID func() (value int64)
	WString      func() string
	WTypeID      func() uint32
	WZero        func() bool
}

func (W _github_com_gotd_td_tg_e2e_FileLocationClass) Decode(b *bin.Buffer) error {
	return W.WDecode(b)
}
func (W _github_com_gotd_td_tg_e2e_FileLocationClass) Encode(b *bin.Buffer) error {
	return W.WEncode(b)
}
func (W _github_com_gotd_td_tg_e2e_FileLocationClass) GetLocalID() (value int) {
	return W.WGetLocalID()
}
func (W _github_com_gotd_td_tg_e2e_FileLocationClass) GetSecret() (value int64) {
	return W.WGetSecret()
}
func (W _github_com_gotd_td_tg_e2e_FileLocationClass) GetVolumeID() (value int64) {
	return W.WGetVolumeID()
}
func (W _github_com_gotd_td_tg_e2e_FileLocationClass) String() string { return W.WString() }
func (W _github_com_gotd_td_tg_e2e_FileLocationClass) TypeID() uint32 { return W.WTypeID() }
func (W _github_com_gotd_td_tg_e2e_FileLocationClass) Zero() bool     { return W.WZero() }

// _github_com_gotd_td_tg_e2e_InputStickerSetClass is an interface wrapper for InputStickerSetClass type
type _github_com_gotd_td_tg_e2e_InputStickerSetClass struct {
	WDecode func(b *bin.Buffer) error
	WEncode func(b *bin.Buffer) error
	WString func() string
	WTypeID func() uint32
	WZero   func() bool
}

func (W _github_com_gotd_td_tg_e2e_InputStickerSetClass) Decode(b *bin.Buffer) error {
	return W.WDecode(b)
}
func (W _github_com_gotd_td_tg_e2e_InputStickerSetClass) Encode(b *bin.Buffer) error {
	return W.WEncode(b)
}
func (W _github_com_gotd_td_tg_e2e_InputStickerSetClass) String() string { return W.WString() }
func (W _github_com_gotd_td_tg_e2e_InputStickerSetClass) TypeID() uint32 { return W.WTypeID() }
func (W _github_com_gotd_td_tg_e2e_InputStickerSetClass) Zero() bool     { return W.WZero() }

// _github_com_gotd_td_tg_e2e_Invoker is an interface wrapper for Invoker type
type _github_com_gotd_td_tg_e2e_Invoker struct {
	WInvokeRaw func(ctx context.Context, input bin.Encoder, output bin.Decoder) error
}

func (W _github_com_gotd_td_tg_e2e_Invoker) InvokeRaw(ctx context.Context, input bin.Encoder, output bin.Decoder) error {
	return W.WInvokeRaw(ctx, input, output)
}

// _github_com_gotd_td_tg_e2e_MessageEntityClass is an interface wrapper for MessageEntityClass type
type _github_com_gotd_td_tg_e2e_MessageEntityClass struct {
	WDecode    func(b *bin.Buffer) error
	WEncode    func(b *bin.Buffer) error
	WGetLength func() (value int)
	WGetOffset func() (value int)
	WString    func() string
	WTypeID    func() uint32
	WZero      func() bool
}

func (W _github_com_gotd_td_tg_e2e_MessageEntityClass) Decode(b *bin.Buffer) error {
	return W.WDecode(b)
}
func (W _github_com_gotd_td_tg_e2e_MessageEntityClass) Encode(b *bin.Buffer) error {
	return W.WEncode(b)
}
func (W _github_com_gotd_td_tg_e2e_MessageEntityClass) GetLength() (value int) { return W.WGetLength() }
func (W _github_com_gotd_td_tg_e2e_MessageEntityClass) GetOffset() (value int) { return W.WGetOffset() }
func (W _github_com_gotd_td_tg_e2e_MessageEntityClass) String() string         { return W.WString() }
func (W _github_com_gotd_td_tg_e2e_MessageEntityClass) TypeID() uint32         { return W.WTypeID() }
func (W _github_com_gotd_td_tg_e2e_MessageEntityClass) Zero() bool             { return W.WZero() }

// _github_com_gotd_td_tg_e2e_PhotoSizeClass is an interface wrapper for PhotoSizeClass type
type _github_com_gotd_td_tg_e2e_PhotoSizeClass struct {
	WDecode  func(b *bin.Buffer) error
	WEncode  func(b *bin.Buffer) error
	WGetType func() (value string)
	WString  func() string
	WTypeID  func() uint32
	WZero    func() bool
}

func (W _github_com_gotd_td_tg_e2e_PhotoSizeClass) Decode(b *bin.Buffer) error { return W.WDecode(b) }
func (W _github_com_gotd_td_tg_e2e_PhotoSizeClass) Encode(b *bin.Buffer) error { return W.WEncode(b) }
func (W _github_com_gotd_td_tg_e2e_PhotoSizeClass) GetType() (value string)    { return W.WGetType() }
func (W _github_com_gotd_td_tg_e2e_PhotoSizeClass) String() string             { return W.WString() }
func (W _github_com_gotd_td_tg_e2e_PhotoSizeClass) TypeID() uint32             { return W.WTypeID() }
func (W _github_com_gotd_td_tg_e2e_PhotoSizeClass) Zero() bool                 { return W.WZero() }

// _github_com_gotd_td_tg_e2e_SendMessageActionClass is an interface wrapper for SendMessageActionClass type
type _github_com_gotd_td_tg_e2e_SendMessageActionClass struct {
	WDecode func(b *bin.Buffer) error
	WEncode func(b *bin.Buffer) error
	WString func() string
	WTypeID func() uint32
	WZero   func() bool
}

func (W _github_com_gotd_td_tg_e2e_SendMessageActionClass) Decode(b *bin.Buffer) error {
	return W.WDecode(b)
}
func (W _github_com_gotd_td_tg_e2e_SendMessageActionClass) Encode(b *bin.Buffer) error {
	return W.WEncode(b)
}
func (W _github_com_gotd_td_tg_e2e_SendMessageActionClass) String() string { return W.WString() }
func (W _github_com_gotd_td_tg_e2e_SendMessageActionClass) TypeID() uint32 { return W.WTypeID() }
func (W _github_com_gotd_td_tg_e2e_SendMessageActionClass) Zero() bool     { return W.WZero() }
