// Code generated by 'yaegi extract github.com/gotd/td/telegram/message/html'. DO NOT EDIT.

package yaegi

import (
	"github.com/gotd/td/telegram/message/html"
	"reflect"
)

func init() {
	Symbols["github.com/gotd/td/telegram/message/html/html"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Bytes":  reflect.ValueOf(html.Bytes),
		"Format": reflect.ValueOf(html.Format),
		"Reader": reflect.ValueOf(html.Reader),
		"String": reflect.ValueOf(html.String),
	}
}
