// Code generated by 'yaegi extract github.com/gotd/td/telegram/query/hasher'. DO NOT EDIT.

package yaegi

import (
	"reflect"

	"github.com/gotd/td/telegram/query/hasher"
)

func init() {
	Symbols["github.com/gotd/td/telegram/query/hasher"] = map[string]reflect.Value{
		// type definitions
		"Hasher": reflect.ValueOf((*hasher.Hasher)(nil)),
	}
}
