// Code generated by 'yaegi extract github.com/gotd/td/telegram/message/styling'. DO NOT EDIT.

package yaegi

import (
	"github.com/gotd/td/telegram/message/styling"
	"reflect"
)

func init() {
	Symbols["github.com/gotd/td/telegram/message/styling"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BankCard":    reflect.ValueOf(styling.BankCard),
		"Blockquote":  reflect.ValueOf(styling.Blockquote),
		"Bold":        reflect.ValueOf(styling.Bold),
		"BotCommand":  reflect.ValueOf(styling.BotCommand),
		"Cashtag":     reflect.ValueOf(styling.Cashtag),
		"Code":        reflect.ValueOf(styling.Code),
		"Custom":      reflect.ValueOf(styling.Custom),
		"Email":       reflect.ValueOf(styling.Email),
		"Hashtag":     reflect.ValueOf(styling.Hashtag),
		"Italic":      reflect.ValueOf(styling.Italic),
		"Mention":     reflect.ValueOf(styling.Mention),
		"MentionName": reflect.ValueOf(styling.MentionName),
		"Perform":     reflect.ValueOf(styling.Perform),
		"Phone":       reflect.ValueOf(styling.Phone),
		"Plain":       reflect.ValueOf(styling.Plain),
		"Pre":         reflect.ValueOf(styling.Pre),
		"Strike":      reflect.ValueOf(styling.Strike),
		"TextURL":     reflect.ValueOf(styling.TextURL),
		"URL":         reflect.ValueOf(styling.URL),
		"Underline":   reflect.ValueOf(styling.Underline),

		// type definitions
		"StyledTextOption": reflect.ValueOf((*styling.StyledTextOption)(nil)),
	}
}
