// Code generated by 'yaegi extract github.com/gotd/td/telegram/query'. DO NOT EDIT.

package yaegi

import (
	"github.com/gotd/td/telegram/query"
	"reflect"
)

func init() {
	Symbols["github.com/gotd/td/telegram/query"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewQuery": reflect.ValueOf(query.NewQuery),

		// type definitions
		"Query": reflect.ValueOf((*query.Query)(nil)),
	}
}
