// Code generated by 'yaegi extract github.com/gotd/td/telegram/message/html'. DO NOT EDIT.

package yaegi

import (
	"reflect"

	"github.com/gotd/td/telegram/message/html"
)

func init() {
	Symbols["github.com/gotd/td/telegram/message/html"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Bytes":       reflect.ValueOf(html.Bytes),
		"Format":      reflect.ValueOf(html.Format),
		"ChunkSource": reflect.ValueOf(html.Reader),
		"String":      reflect.ValueOf(html.String),
	}
}
