// Code generated by 'yaegi extract github.com/gotd/td/telegram/query/dialogs'. DO NOT EDIT.

package yaegi

import (
	"context"
	"reflect"

	"github.com/gotd/td/telegram/query/dialogs"
	"github.com/gotd/td/tg"
)

func init() {
	Symbols["github.com/gotd/td/telegram/query/dialogs"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewIterator":     reflect.ValueOf(dialogs.NewIterator),
		"NewQueryBuilder": reflect.ValueOf(dialogs.NewQueryBuilder),

		// type definitions
		"Elem":                   reflect.ValueOf((*dialogs.Elem)(nil)),
		"GetDialogsQueryBuilder": reflect.ValueOf((*dialogs.GetDialogsQueryBuilder)(nil)),
		"Iterator":               reflect.ValueOf((*dialogs.Iterator)(nil)),
		"Query":                  reflect.ValueOf((*dialogs.Query)(nil)),
		"QueryBuilder":           reflect.ValueOf((*dialogs.QueryBuilder)(nil)),
		"QueryFunc":              reflect.ValueOf((*dialogs.QueryFunc)(nil)),
		"Request":                reflect.ValueOf((*dialogs.Request)(nil)),

		// interface wrapper definitions
		"_Query": reflect.ValueOf((*_github_com_gotd_td_telegram_query_dialogs_Query)(nil)),
	}
}

// _github_com_gotd_td_telegram_query_dialogs_Query is an interface wrapper for Query type
type _github_com_gotd_td_telegram_query_dialogs_Query struct {
	WQuery func(ctx context.Context, req dialogs.Request) (tg.MessagesDialogsClass, error)
}

func (W _github_com_gotd_td_telegram_query_dialogs_Query) Query(ctx context.Context, req dialogs.Request) (tg.MessagesDialogsClass, error) {
	return W.WQuery(ctx, req)
}
